### ISSUE TITLE
Update to the latest ollama version

### ISSUE THREAD

**Issue by ghost** [abysssol/ollama-flake#1] opened 2024-01-28 09:11 UTC
Hi. ollama has changed a lot since 0.1.17. ollama doesn't call the llama-cpp's executable on its own anymore but use their libraries. And very recently rocm support.

Any plans on updating your flake to the latest ollama version?

**Comment by abysssol** [comment] 2024-01-29 04:41
Hi! Thank you for notifying me of this, I was unaware of recent ollama development.
I originally made this flake to try out the mixtral dolphin model, but I found the model to be disappointing. Thus, I stopped using it and ollama.

I'll try to update to ollama master, but I'm not a nix (or go) expert, so if the upstream changes are too drastic, I may be unable to make it work.
I'll see what I can do, and I'll update this issue accordingly. Thank you for your patience.

**Comment by abysssol** [comment] 2024-02-03 02:44
## Status Update

I've finally figured out how to get ollama to build, but only with it's default cpu based configuration.
I'll try to get it to trigger it's rocm build configuration, but if I'm unable to, I'll commit a version that just builds for the cpu and archive the repo.
If I can get rocm to work, then I'll start thinking about cuda.

**Comment by abysssol** [comment] 2024-02-03 14:31
## Status Update

I got ollama to build with rocm, and I confirmed that it is using my gpu. After I sleep, I'll clean up the flake and push a version to github with a couple package options: one for the default cpu only build, and one for the rocm build.
<details>
  <summary>
  One thing to note: I did a little testing, and it turns out that llama/ollama is memory bound, at least with my gpu.
  Memory traffic is taking up an enormous amount of time and is bottlenecking the gpu and cpu.
  <br><em>click to read more</em>
  </summary>

Gpu utilization was quite low (10-15 percent of maximum load), even though the model was continually producing output and seemed to me like it should be able to go faster. I looked closer, and found that memory was constantly moving, which was blocking the gpu pipeline and leading to low gpu use.

I'm not sure what the cause is:
 - is it inherent to the llama architecture, or just the particular implementation?
   - is this common in neural networks?
 - how much do the model weights play a role? (I only tested dolphin-mixtral so far)
 - would more vram help? (my gpu has 16 gibibytes, 14 of which is free for ollama to use, but ollama only uses 12, so I think more wouldn't help)
 - is there some build option or compiler option that could help?
 
Whatever the case, this means that ollama can't scale to better hardware past a certain point, and thus the speed of responses is capped. Maybe I'm just missing some information, and there's some way to fix this, but I think not.
</details>

**Comment by abysssol** [comment] 2024-02-04 18:06
## Status Update

I finally pushed the updated flake to github. It currently supports building for cpu or rocm, probably only for x86 linux. I'll try to get cuda to work, but it's not a priority for now.
Try building the flake and tell me if it works correctly on your machine.

**Comment by ghost** [comment] 2024-02-05 09:18
Tested both. Seems to be working fine so far! Thank you :D

Waiting for cuda support :)

**Comment by abysssol** [comment] 2024-02-05 17:42
Good; nix is usually quite reproducible, but due to the hardware dependent nature of rocm (and cuda), I wasn't as confident in it's correctness this time.
I'll get cuda working if I can, but the only machine with an nvidia gpu that I have any access to isn't mine anymore, so it'll take a while for me to borrow it so I can test building with cuda.

Also, unrelated, do you have any comments on the documentation/readme? Anything that you find confusing, or that you think is missing, or that could be better in some other way. I personally find that documentation is more important than most people realize (and I found nix tends to be rather deficient in it's documentation).

**Comment by abysssol** [comment] 2024-02-06 23:54
I got ollama to build with cuda libraries, but when I tried to run it on an nvidia gpu, it was unable to use cuda and had to fall back to cpu. I'm not sure if this is due to the gpu not being compatible with cuda, or if the flake is wrong somehow.
If you have an nvidia gpu, could you build the latest version on github and tell me if it uses your gpu?

**Comment by TanvirOnGH** [comment] 2024-02-07 09:21
Latest ollama version from github works fine my end and uses the nvidia gpu as expected.

**Comment by ghost** [comment] 2024-02-07 09:22
> Good; nix is usually quite reproducible, but due to the hardware dependent nature of rocm (and cuda), I wasn't as confident in it's correctness this time. I'll get cuda working if I can, but the only machine with an nvidia gpu that I have any access to isn't mine anymore, so it'll take a while for me to borrow it so I can test building with cuda.
> 
> Also, unrelated, do you have any comments on the documentation/readme? Anything that you find confusing, or that you think is missing, or that could be better in some other way. I personally find that documentation is more important than most people realize (and I found nix tends to be rather deficient in it's documentation).

The documentation is pretty straight-forward. Easy to following along :D

**Comment by ghost** [comment] 2024-02-07 10:15
> I got ollama to build with cuda libraries, but when I tried to run it on an nvidia gpu, it was unable to use cuda and had to fall back to cpu. I'm not sure if this is due to the gpu not being compatible with cuda, or if the flake is wrong somehow. If you have an nvidia gpu, could you build the latest version on github and tell me if it uses your gpu?

Awesome, CUDA works. (NVIDIA-SMI 545.29.06,              Driver Version: 545.29.06,    CUDA Version: 12.3)

## Running tinydolphin

ollama logs:
```lua
llm_load_tensors: offloading 22 repeating layers to GPU
llm_load_tensors: offloading non-repeating layers to GPU
llm_load_tensors: offloaded 23/23 layers to GPU
llm_load_tensors:        CPU buffer size =    35.16 MiB
llm_load_tensors:      CUDA0 buffer size =   571.37 MiB
```

nvtop:
![image](https://github.com/abysssol/ollama-flake/assets/138336161/ecb1fdbf-8283-4a97-b91b-f5d3419182e0)

## Running openchat

ollama logs:
```lua
llm_load_tensors: offloading 32 repeating layers to GPU
llm_load_tensors: offloading non-repeating layers to GPU
llm_load_tensors: offloaded 33/33 layers to GPU
llm_load_tensors:        CPU buffer size =    70.32 MiB
llm_load_tensors:      CUDA0 buffer size =  3847.56 MiB
```

nvtop:
![image](https://github.com/abysssol/ollama-flake/assets/138336161/172e7d61-63bd-4828-8331-71c7bfa8fc01)
![image](https://github.com/abysssol/ollama-flake/assets/138336161/79a3811b-44f9-4bbd-9660-a4db3206eadf)

**Comment by abysssol** [comment] 2024-02-07 17:50
Great to hear! Thank you for testing it.
I pushed a commit last minute that added the cuda runtime to the LD_LIBRARY_PATH wrapper script. I think that may have been what fixed it. I'll have to check if it runs right now on the nvidia gpu I tested, or if that gpu just doesn't support cuda.
Would you try to build and run the previous commit (c8a84114) and see if it runs right without the cuda runtime? I'm not sure if it's actually necessary or not.
``` shell
nix shell github:abysssol/ollama-flake/c8a84114
```

The flake now supports the current most recent version of ollama (0.1.23) with full rocm and cuda support. Only darwin/macOS support remains, and I feel that would be best left for another issue (if ever).
So, I'm closing this issue as completed.

**Closed as completed by abysssol** 2024-02-07 17:50 UTC

**Comment by abysssol** [comment] 2024-02-07 22:35
I tested the latest commit that added the cuda runtime (on a [gtx 1060](
https://pcpartpicker.com/product/P8Crxr/gigabyte-geforce-gtx-1060-3gb-3gb-mini-itx-oc-video-card-gv-n1060ixoc-3gd)), but ollama was still unable to detect the gpu. This makes me think that the gpu is currently unsupported, and makes me suspect that adding the cuda runtime to the wrapper script was actually unnecessary.
I would appreciate it if you would test commit c8a84114 (without cuda runtime) sometime and see if ollama can still detect and use your gpu. It's not urgent since the current commit is working, but I don't want the flake to have useless code. Thank you.

**Comment by ghost** [comment] 2024-02-08 17:43
@abysssol Tested commit c8a8411. CUDA still works.

Also v0.1.24 is out!

**Comment by abysssol** [comment] 2024-02-08 22:22
Thank you @TanvirOnGH. I'll revert the unnecessary commit and update to the newest version sometime soon.
